version: '3'
services:
  emqx1:
    image: emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io]"
    volumes:
      - ./emqx1/etc:/opt/emqx/etc
      - ./emqx1/data:/opt/emqx/data
      - ./emqx1/log:/opt/emqx/log
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io
  emqx2:
    image: emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io]"
    volumes:
      - ./emqx2/etc:/opt/emqx/etc
      - ./emqx2/data:/opt/emqx/data
      - ./emqx2/log:/opt/emqx/log
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.io
networks:
    emqx-bridge:
      driver: bridge