version: '3'
services:      
  db:
    image: 'mysql/mysql-server:5.7'
    restart: always       
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "qq1203943228"   
    networks:
      - net-spring-db                  
    user: root   
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/my.cnf:/etc/my.cnf  
      - ./mysql/sql:/docker-entrypoint-initdb.d/
    ports: 
      - "3306:3306"  
  redis:
    restart: always
    image: redis:4.0.9
    container_name: redis            
    command: redis-server --requirepass "ZV5ut2FNPp/5iqE1l5feIg=="     
    networks:
      - net-spring-db     
    volumes:
      -  ./redis/redis.conf:/etc/redis/redis.conf 
      -  ./redis/data:/data 
    ports: 
      - "6379:6379"
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: rabbitmq
    ports:
     - "15672:15672"
     - "5671-5672:5671-5672"
    restart: always
    environment: 
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
     - '2181:2181' 
    volumes:
 #    - /etc/localtime:/etc/localtime
     - ./zk/conf/zoo.cfg:/opt/zookeeper-3.4.9/conf/zoo.cfg
     - ./zk/data:/opt/zookeeper-3.4.9/data
     - ./zk/log:/opt/zookeeper-3.4.9/logs
     - ./zk/zkServer.sh:/opt/zookeeper-3.4.9/bin/zkServer.sh    --privileged=true 
    networks: 
     - net-spring-db    
  mongo:
    container_name: mongo         
    image: mongo
    ports:
      - "27777:27017"          
    environment:
        - MONGO_INITDB_ROOT_USERNAME=fulln
        - MONGO_INITDB_ROOT_PASSWORD=mongo2451
    volumes:     
      - ./mongo/config/:/data/configdb
      - ./mongo/db/:/data/db    
networks:
  net-spring-db:   
    driver: bridge  
