version: '3.1'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example       
    volumes:        
      - /etc/localtime:/etc/localtime
      - ./config/:/data/configdb
      - ./db:/data/db      
  mongo-express:
    image: mongo-express
    ports:
      - 8881:8081   
    depends_on:
      - mongo     
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
